# Generated by Django 4.0.4 on 2022-05-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='album',
            name='label_number',
            field=models.CharField(default='DG-', max_length=10),
        ),
    ]
