# Generated by Django 4.0.4 on 2022-05-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100)),
                ('purpose', models.TextField(max_length=3000)),
                ('links', models.CharField(max_length=200)),
            ],
        ),
    ]
