# Generated by Django 4.0.4 on 2022-06-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500)),
                ('body', models.TextField(max_length=1500000)),
                ('time_created', models.DateTimeField()),
                ('author', models.CharField(max_length=32)),
                ('picture', models.CharField(default='COMMING SOON', max_length=100)),
            ],
        ),
    ]
