# Generated by Django 4.0.4 on 2022-05-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=120)),
                ('album', models.CharField(max_length=120)),
                ('genre', models.CharField(choices=[('Dungeon_synth', 'Dungeon synth'), ('Black Metal', 'Black Metal')], default='Dungeon_synth', max_length=40)),
                ('release_date', models.DateTimeField()),
                ('country', models.CharField(max_length=30)),
                ('physical_type', models.CharField(choices=[('TAPE', 'Tape'), ('CD', 'CD')], default='TAPE', max_length=15)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('label_number', models.TextField(default='0')),
            ],
        ),
    ]
