# Generated by Django 4.0.4 on 2022-06-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_album_description_alter_album_label_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_art_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
