# Generated by Django 4.0.4 on 2022-06-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_album_cover_art_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='slug-test'),
            preserve_default=False,
        ),
    ]
