# Generated by Django 4.0.4 on 2022-06-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_album_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.CharField> + <django.db.models.fields.CharField>'),
        ),
    ]
