# Generated by Django 4.0.4 on 2022-06-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_album_quantity_alter_album_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='quantity',
        ),
    ]
