# Generated by Django 4.0.4 on 2022-07-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_useritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
